name: Add Comment to New Python Files and Update new_files.txt

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'

jobs:
  update_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Determine previous commit
      id: prev_commit
      run: |
        if git rev-parse HEAD^ > /dev/null 2>&1; then
          echo "PREV_COMMIT=$(git rev-parse HEAD^)" >> $GITHUB_ENV
        else
          echo "PREV_COMMIT=$(git rev-list --max-parents=0 HEAD)" >> $GITHUB_ENV
        fi

    - name: Find new Python files
      id: find_files
      run: |
        git diff --name-only ${{ env.PREV_COMMIT }} HEAD > new_files.txt
        grep '.py$' new_files.txt || echo "No new Python files found" && exit 0

    - name: Add comment to new Python files
      run: |
        for file in $(cat new_files.txt); do
          if [[ $file == *.py ]]; then
            echo '# Hello, this is a Python file' | cat - "$file" > temp && mv temp "$file"
            echo "$file" >> new_files.txt
          fi
        done

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Add comment to new Python files and update new_files.txt'
        git push origin main
