name: Add Comment to New Python Files and Update text_files.txt

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'

jobs:
  add_comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Determine previous commit
      id: prev_commit
      run: |
        if git rev-parse HEAD^ > /dev/null 2>&1; then
          echo "PREV_COMMIT=$(git rev-parse HEAD^)" >> $GITHUB_ENV
        else
          echo "PREV_COMMIT=$(git rev-list --max-parents=0 HEAD)" >> $GITHUB_ENV
        fi

    - name: Find new Python files
      id: find_files
      run: |
        git diff --name-only ${{ env.PREV_COMMIT }} HEAD > new_files.txt
        if grep '.py$' new_files.txt; then
          echo "has_new_files=true" >> $GITHUB_ENV
        else
          echo "has_new_files=false" >> $GITHUB_ENV
        fi

    - name: Check new files
      id: check_files
      run: |
        if [ -s new_files.txt ]; then
          echo "has_new_files=true" >> $GITHUB_ENV
        else
          echo "has_new_files=false" >> $GITHUB_ENV
        fi

    - name: Add comment to new Python files
      if: env.has_new_files == 'true'
      run: |
        for file in $(cat new_files.txt); do
          if [[ $file == *.py ]]; then
            echo '# This is a new Python file' | cat - "$file" > temp && mv temp "$file"
          fi
        done

    - name: Update text_files.txt with new Python filenames
      if: env.has_new_files == 'true'
      run: |
        touch text_files.txt
        for file in $(cat new_files.txt); do
          if [[ $file == *.py ]]; then
            echo "$file" >> text_files.txt
          fi
        done

    - name: Commit changes
      if: env.has_new_files == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Add comment to new Python files and update text_files.txt'
        git push origin main
